FROM node:20-alpine

WORKDIR /app

COPY package*.json ./
RUN npm install

# Copy prisma schema specifically so we can generate client
COPY prisma ./prisma/
RUN npx prisma generate

COPY . .

EXPOSE 8080

CMD ["npm", "run", "dev"]
